ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManager.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
ProjectManager/ProjectManager/AppDelegate.swift
ProjectManager/ProjectManager/GoogleService-Info.plist

Firebase 설치

---

ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManager.xcodeproj/xcshareddata/xcschemes/ProjectManager.xcscheme
ProjectManager/ProjectManager/Source/Common/Utils/Extension/Double+Formatter.swift
ProjectManager/ProjectManager/Source/Common/Utils/Extension/String+Formatter.swift
ProjectManager/ProjectManager/Source/Domain/Entities/Task.swift
ProjectManager/ProjectManager/Source/Domain/Entities/TaskEntity.swift
ProjectManager/ProjectManager/Source/Domain/Entities/Translater.swift
ProjectManager/ProjectManagerTests/Common/TaskDummy.swift
ProjectManager/ProjectManagerTests/Common/TaskEntityDummy.swift
ProjectManager/ProjectManagerTests/TranslaterTests/TranslaterTests.swift

- Entity, Model, Translater 추가
- Translater 내의 Entity -> Model, Model -> Entity 변환기능 추가
- Translater 단위테스트
task -> taskEntity의 경우 실패 케이스 없음.

12 feature entity model 추가

---

ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManager/Source/Domain/Interfaces/Repositories/TaskRepository.swift
ProjectManager/ProjectManagerTests/Common/MockTaskRepository.swift

- TaskRepository 구현 완료 (CRUD)
- MockTaskRepository 구현 완료

feat: TaskRepository 및 MockTaskRepository 구현

---

ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditTaskDelegate.swift

- CUD 작업이 완료되고 fetch UseCase내의 배열 업데이트 용 프로토콜
- didEndEdit(task: Task) 추가

feat: DidEndEditTaskDelegate 추가

---

ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManager/Source/Domain/UseCases/CreateUseCase.swift
ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditTaskDelegate.swift
ProjectManager/ProjectManagerTests/UseCaseTests/CreateUseCaseTests.swift

#15 
- addTask 추가
- delegate, repository 외부에서 주입
- 단위테스트 추가

Create use case 추가

---

ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManager/Source/Domain/Entities/Task.swift
ProjectManager/ProjectManager/Source/Domain/Entities/TaskEntity.swift
ProjectManager/ProjectManager/Source/Domain/Entities/Translater.swift
ProjectManager/ProjectManager/Source/Domain/UseCases/FetchTasksUseCase.swift

- FetchTasksUseCase Type 구현
- FetchTasksUseCase에서 DidEndEditTaskDelegate 채택
- Unit Test
**이유**: DidEndEditTaskDelegate 리팩토링 후 추가 작업 진행.

[feat] FetchTasksUseCase

---

ProjectManager/ProjectManager/Source/Domain/UseCases/CreateUseCase.swift
ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditTaskDelegate.swift

Close #27 
delegate를 3개로 분리
- DidEndEditTaskDelegate
- DidEndUpdatingDelegate
- DidEndDeletingDelegate

refactor: delegate를 3개로 분리

---

ProjectManager/ProjectManager/Source/Domain/UseCases/CreateUseCase.swift
ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditTaskDelegate.swift

resolved #29 
- CreateUseCase의 네이밍 수정

refactor: delegate 네이밍 변경

---

ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManagerUnitTests/Common/TaskDummy.swift
ProjectManager/ProjectManagerUnitTests/Common/TaskEntityDummy.swift
ProjectManager/ProjectManagerUnitTests/UseCaseTests/DeleteUseCaseTests.swift

#35 
Mock 데이터의 ID 값을 테스트 하기쉽도록 지정.
- 삭제하는 경우
- 삭제 실패하는 경우

35 단위테스트 deleteusecase 테스트

---

ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManager/Source/Domain/UseCases/UpdateUseCase.swift
ProjectManager/ProjectManagerUnitTests/UseCaseTests/UpdateUseCaseTests.swift

UpdateUseCase 구현
기존엔 UpdateTaskStateUseCase와 UpdateTaskInformationUseCase로 나누어 구현하려고 했으나 하나의 UseCase로 구현하기로 이야기 나누었기 때문에 하나의 UseCase로 구현함.

feature: UpdateUseCase 구현

---

ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManager/Source/Domain/UseCases/Delegate/DidEndEditingTaskDelegate.swift
ProjectManager/ProjectManager/Source/Domain/UseCases/DeleteUseCase.swift
ProjectManager/ProjectManager/Source/Domain/UseCases/FetchTasksUseCase.swift
ProjectManager/ProjectManagerUnitTests/UseCaseTests/DeleteUseCaseTests.swift
ProjectManager/ProjectManagerUnitTests/UseCaseTests/FetchTasksUseCaseTests.swift

refactor: FetchTasksUseCase DidEndEditingTaskDelegate 채택 및 Unit Test 추가

---

ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskListScene/TaskListViewModel.swift

- 프로퍼티
- BehaviorRelay<[Task.State: [Task]]> Type 구현 완료
- FetchTasksUseCase Type 구현 완료
- DeleteTaskUseCase Type 구현 완료
- Event에 대한 Input Type 구현 완료
- 메서드
- bind(input: ) 구현 완료

feature: TaskListViewModel 추가

---

ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskEditScene/TaskEditViewModel.swift

Closes #42 
Input, Output
transform(input: disposeBag:) -> Output
bind(input: , disposBag:)

42 feature taskeditviewmodel 추가

---

ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskCreateScene/TaskCreateViewModel.swift

Closes #41 
Input, Output
transform(input: disposBag:) -> Output
bind(input: , disposBag:)
line 41. 캡처 여부, 아마 필요없을 듯 한데 체크 한번만 부탁드립니다.
line 83. 정상적인 빌드를 위해 Task로 만들어 준 후 usecase 실행합니다. 이후 변경해야하니 이슈 남겨놓겠습니다

41 feature taskcreateviewmodel 추가

---

ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskDetailScene/TaskDetailViewModel.swift

Closes #47 
TaskDetailViewModel 생성
input

[feature] TaskDetailViewModel 생성

---

ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/StateUpdatePopOverScene/StateUpdateViewModel.swift

- 프로퍼티
- UpdateTaskUseCase Type 구현 완료
- Event에 대한 Input Type 구현 완료
- 메서드
- bind(input: ) 구현 완료

feature: StateUpdateViewModel 추가

---

ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskCreateScene/TaskCreateViewModel.swift
ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/TaskEditScene/TaskEditViewModel.swift

Create, Update시 버튼 활성화/비활성화를 위한 Output 구현 완료
- Title, Content가 있을때만 true
- 정상적인 빌드

feat: Create, Update시 버튼 활성화/비활성화를 위한 Output

---

ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManager/Source/Domain/UseCases/DefaultUpdateTaskUseCase.swift
ProjectManager/ProjectManagerUnitTests/UseCaseTests/FetchTasksUseCaseTests.swift
ProjectManager/ProjectManagerUnitTests/UseCaseTests/UpdateTaskUseCaseTests.swift
ProjectManager/ProjectManagerUnitTests/ViewModelTests/Mock/UpdateTaskUseCaseMock.swift
ProjectManager/ProjectManagerUnitTests/ViewModelTests/TaskEditViewModelTests.swift

TaskEditViewModel 테스트
- TaskEditViewModel 테스트 완료
- UpdateTaskUseCaseMock Type 구현
- 정상적인 빌드

단위테스트: TaskEditViewModel 테스트

---

ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManager/Source/Domain/UseCases/DefaultDeleteTaskUseCase.swift
ProjectManager/ProjectManager/Source/Domain/UseCases/DefaultFetchTasksUseCase.swift
ProjectManager/ProjectManagerUnitTests/UseCaseTests/DeleteTaskUseCaseTests.swift
ProjectManager/ProjectManagerUnitTests/UseCaseTests/FetchTasksUseCaseTests.swift
ProjectManager/ProjectManagerUnitTests/ViewModelTests/Mock/DeleteTaskUseCaseMock.swift
ProjectManager/ProjectManagerUnitTests/ViewModelTests/Mock/FetchTasksUseCaseMock.swift
ProjectManager/ProjectManagerUnitTests/ViewModelTests/TaskListViewModelTests.swift

Closes #56 
- viewWillAppear 옵저버 값에 따른 tasks 값 존재 여부 테스트

56 단위테스트 tasklistviewmodel 테스트

---

ProjectManager/ProjectManager.xcodeproj/project.pbxproj
ProjectManager/ProjectManager/Source/Domain/UseCases/DefaultCreateTaskUseCase.swift
ProjectManager/ProjectManagerUnitTests/UseCaseTests/CreateTaskUseCaseTests.swift
ProjectManager/ProjectManagerUnitTests/UseCaseTests/FetchTasksUseCaseTests.swift
ProjectManager/ProjectManagerUnitTests/ViewModelTests/Mock/CreateTaskUseCaseMock.swift
ProjectManager/ProjectManagerUnitTests/ViewModelTests/TaskCreateViewModelTests.swift

Closes #57 
- title, content 값에 따른 isFill 조건 판단 테스트
- 완료 버튼 동작에 따른 isSuccess 조건 발동 테스트

57 단위테스트 taskcreateviewmodel 테스트

---

ProjectManager/ProjectManager/Source/Presentation/KanbanBoard/StateUpdatePopOverScene/StateUpdateViewModel.swift
ProjectManager/ProjectManagerUnitTests/ViewModelTests/StateUpdateViewModelTests.swift

StateUpdateViewModel 테스트
- StateUpdateViewModel 수정
- StateUpdateViewModel 테스트
- 정상적인 빌드

단위테스트: StateUpdateViewModel 테스트
